### ISSUE TITLE
Permission Issue

### ISSUE THREAD

**Issue by kernelbricker09** [karthik558/Kernel-Compile-Script#1]
Bro , this script is just awesome cuz its just light weight and very easy to configure and the codes.. i just have 1 doubt , bro why u giving chmod +x permission ?? just bash is enought right , or is there any specific reason for giving full permission..?

**Comment by karthik558** [comment]
Just , bash is enough bro , if u give all permission then u can easily run it. like ./run.sh instead of bash run.sh (anyway not much diff)..
